name: yoldas
description: Yoldaş - Yol yardım uygulaması
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6                             # ✅ API istekleri için
  flutter_secure_storage: ^9.0.0           # ✅ Token saklamak için
  shared_preferences: ^2.2.2               # ✅ Local storage için
  network_info_plus: ^4.1.0                # ✅ IP adresi tespiti için
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  url_launcher: ^6.3.1
  app_links: ^3.4.1  # uni_links yerine app_links kullanacağız
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.png
    - assets/erkek.png
    - assets/kadin.png
    - assets/icon/
    - assets/splash/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
