name: yoldas
description: Yoldaş - Yol yardım uygulaması
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6                             # ✅ API istekleri için
  flutter_secure_storage: ^9.0.0           # ✅ Token saklamak için
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  url_launcher: ^6.3.1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/kadin.png
    - assets/erkek.png
